include:
  - project: uniprot/variation/protvar-deploy
    ref: main
    file: /ci-templates/gitlab-ci-template.yml

# Default
variables:
  BE_API: "https://wwwdev.ebi.ac.uk/ProtVar/api"

stages:
#  - test
  - build_static_assets
  - build_docker_image
  - deploy

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      variables:
        BE_API: "https://www.ebi.ac.uk/ProtVar/api"
    - if: '$CI_COMMIT_BRANCH == "dev"'
      variables:
        BE_API: "https://wwwdev.ebi.ac.uk/ProtVar/api"
    - if: '$CI_COMMIT_BRANCH == "int"'
      variables:
        BE_API: "https://wwwint.ebi.ac.uk/ProtVar/api"
    - when: always

.js:
  image: dockerhub.ebi.ac.uk/uniprot/variation/protvar-deploy/node
  before_script:
    - node --version
    - npm --version
    - yarn --version
    - yarn install

#test:
#  stage: test
#  script:
#    - echo "skipping test for now";

build_static_assets:
  only:
    refs: [main, dev, int]
  extends: .js
  stage: build_static_assets
  script:
    - echo "REACT_APP_GIT_BRANCH=${CI_COMMIT_BRANCH}" >> .env.local
    - echo "REACT_APP_API_BASE_URL=${BE_API}" >> .env.local
    - yarn build
  artifacts:
    paths:
      - build/

build_docker_image:
  only:
    refs: [main, dev, int]
  extends: .build_docker
  stage: build_docker_image

int-deploy:
  rules:
    - if: '$CI_COMMIT_BRANCH == "int"'
      when: manual
  extends: .deploy
  stage: deploy
  script:
    - ./protvar-deploy/scripts/deploy.sh "int" "protvar-fe" "${CI_COMMIT_SHORT_SHA}"

dev-deploy:
  only:
    refs: [dev]
  extends: .deploy
  stage: deploy
  script:
    - ./protvar-deploy/scripts/deploy.sh "dev" "protvar-fe" "${CI_COMMIT_SHORT_SHA}"

main-deploy:
  only:
    refs: [main]
  extends: .deploy
  stage: deploy
  script:
    - ./protvar-deploy/scripts/deploy.sh "pub" "protvar-fe" "${CI_COMMIT_SHORT_SHA}"
