export const ABOUT = "/about"
export const CONTACT = "/contact"
export const RESULT = "/result" //[/:input]
export const QUERY = "/query"
export const HOME = "/"
export const API_ERROR = "/error"
export const DOWNLOAD = "/download"
export const HELP = "/help"
export const RELEASE = "/release"