export const PDB_URL_INTERFACE_BY_ID = "https://www.ebi.ac.uk/pdbe/entry/pdb/";
export const PDB_URL_INTERFACE_BY_PROTEIN = "https://www.ebi.ac.uk/pdbe/pdbe-kb/proteins/";
export const ALPHAFOLD_URL = "https://alphafold.ebi.ac.uk/api/prediction/";
export const ALPHAFOLD_URL_INTERFACE_BY_PROTEIN = "https://alphafold.ebi.ac.uk/entry/";
export const ENSEMBL_GENE_RUL = "https://www.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g="
export const ENSEMBL_GENE_URL = "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g="
export const ENSEMBL_CHRM_URL = "https://www.ensembl.org/Homo_sapiens/Location/Chromosome?r="
export const ENSEMBL_VIEW_URL = "https://www.ensembl.org/Homo_sapiens/Location/View?r="
export const ENSEMBL_ASML_URL = "https://www.ensembl.org/Homo_sapiens/Tools/AssemblyConverter?db=core"
export const RHEA_URL = "https://www.rhea-db.org/rhea/";
export const INTACT_URL = "https://www.ebi.ac.uk/intact/search?query="
export const UNIPROT_ACCESSION_URL = "https://www.uniprot.org/uniprot/"
export const CADD_INFO_URL = "https://cadd.gs.washington.edu/info"
export const VCF_FORMAT_INFO_URL = "https://github.com/ebi-uniprot/protvar-be/blob/main/docs/vcf-format.md"
export const DBSNP_URL = "https://www.ncbi.nlm.nih.gov/snp/"
export const CLINVAR_RCV_URL = "https://www.ncbi.nlm.nih.gov/clinvar/"
export const CLINVAR_VCV_URL = "https://www.ncbi.nlm.nih.gov/clinvar/variation/"
export const COSMIC_URL = "https://cancer.sanger.ac.uk/cosmic/search?q="
export const HUMSAVAR_URL = "https://www.uniprot.org/help/humsavar_change"
