export const PROTEINS = {
  CATALYTIC_ACTIVITY: 'CATALYTIC ACTIVITY',
  ACTIVITY_REGULATION: 'ACTIVITY REGULATION',
  SUBUNIT: 'SUBUNIT',
  INTERACTION: 'INTERACTION',
  SUBCELLULAR_LOCATION: 'SUBCELLULAR LOCATION',
  DOMAIN: 'DOMAIN',
  PTM: 'PTM',
  SIMILARITY: 'Family',
  WEBRESOURCE: 'Additional Resource'
};

export const FEATURES = {
  INIT_MET: 'Cleaved Initiator Methionine',
  SIGNAL: 'Signal Peptide',
  TRANSIT: 'Cleaved Transit Peptide',
  PROPEP: 'Propeptide',
  CHAIN: 'Chain',
  PEPTIDE: 'Peptide',
  TOPO_DOM: 'Transmembrane Protein Topological Region',
  TRANSMEM: 'Helical Transmembrane Peptide',
  DOMAIN: 'Functional Domain',
  REPEAT: 'Repeated Sequence',
  REGION: 'Region',
  COILED: 'Coiled-coil Region',
  MOTIF: 'Functional Motif',
  COMPBIAS: 'AA Composition Bias',
  DNA_BIND: 'DNA Binding Residue',
  NP_BIND: 'Nucleotide Phosphate Binding Residue',
  ACT_SITE: 'Active Site Residue',
  METAL: 'Metal Ion Binding Site Residue',
  BINDING: 'Binding Site Residue',
  CA_BIND: 'Calcium Binding Residue',
  ZN_FING: 'Zinc Finger Residue',
  SITE: 'Functionally Important Residue',
  MOD_RES: 'PTM Modified Residue',
  LIPID: 'PTM bound Lipid',
  PTM: 'PTM',
  MUTAGEN: 'Mutagenesis',
  CATALYTIC_ACTIVITY: 'Catalytic Activity',
  ACTIVITY_REGULATION: 'ACTIVITY REGULATION',
  SUBUNIT: 'SUBUNIT',
  INTERACTION: 'INTERACTION',
  SUBCELLULAR_LOCATION: 'SUBCELLULAR LOCATION',
  SIMILARITY: 'Family',
  WEBRESOURCE: 'Additional Resource',
  HELIX: 'Helix'
};

export const AMINO_ACID_FULL_NAME = {
  ala: {name: "Alanine", oneLetter: "a"},
  arg: {name: "Arginine", oneLetter: "r"},
  asn: {name: "Asparagine", oneLetter: "n"},
  asp: {name: "Aspartic acid", oneLetter: "d"},
  cys: {name: "Cysteine", oneLetter: "c"},
  gln: {name: "Glutamine", oneLetter: "q"},
  glu: {name: "Glutamic acid", oneLetter: "e"},
  gly: {name: "Glycine", oneLetter: "g"},
  his: {name: "Histidine", oneLetter: "h"},
  ile: {name: "Isoleucine", oneLetter: "i"},
  leu: {name: "Leucine", oneLetter: "l"},
  lys: {name: "Lysine", oneLetter: "k"},
  met: {name: "Methionine", oneLetter: "m"},
  phe: {name: "Phenylalanine", oneLetter: "f"},
  pro: {name: "Proline", oneLetter: "p"},
  ser: {name: "Serine", oneLetter: "s"},
  thr: {name: "Threonine", oneLetter: "t"},
  trp: {name: "Tryptophan", oneLetter: "w"},
  tyr: {name: "Tyrosine", oneLetter: "y"},
  val: {name: "Valine", oneLetter: "v"},
  ter: {name: "Stop", oneLetter: "*"},
// extended - no img
  glx: {name: "Glutamine or glutamic acid", oneLetter: "z"},
  asx: {name: "Asparagine or aspartic acid", oneLetter: "b"}, // no img
};
